FROM ubuntu
RUN apt-get update && apt-get install openssh-server -y && apt-get install openssh-client -y && apt-get install python3 
RUN apt-get update && apt install ansible -y  
WORKDIR /root/.ssh/
RUN chmod 700 /root/.ssh && chown root:root /root/.ssh
COPY id_rsa .
RUN chmod 600 id_rsa && chown root:root id_rsa
EXPOSE 22
